app_id: "02b2d61a-3ebc-42ff-be51-a29c85e5149f"
app_secret: "rqjd-Yipp?7D5p78zfOUya=c.43/SXGf"
redirect: "https://hochart.azurewebsites.net/chart/callback"
scopes: "openid profile offline_access user.read GroupMember.Read.All User.Read.All Group.ReadWrite.All"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"
