app_id: "e2814636-9345-4add-a14d-9bd69471688c"
app_secret: "3pxCceR54wgfbgmuzUts4SQ]NY/hpG.:"
redirect: "https://teamschart.azurewebsites.net/chart/callback"
scopes: "openid profile offline_access user.read calendars.read GroupMember.Read.All User.Read.All Group.ReadWrite.All"
authority: "https://login.microsoftonline.com/common"
authorize_endpoint: "/oauth2/v2.0/authorize"
token_endpoint: "/oauth2/v2.0/token"